# Generated by Django 4.0.5 on 2022-06-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0002_mendimi_delete_sherbimi'),
    ]

    operations = [
        migrations.CreateModel(
            name='galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
