# Generated by Django 4.0.5 on 2022-06-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0006_remove_galeria_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='description',
            field=models.CharField(default='pershkrimi', max_length=255),
        ),
    ]
