# Generated by Django 4.0.5 on 2022-06-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0009_veneers_titulli'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invisalign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(default='Invisalign', max_length=255)),
                ('descriptioN', models.TextField()),
                ('foto', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
