# Generated by Django 4.0.5 on 2022-06-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0011_ortodonci'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zbardhimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(default='Zbardhimi I Dhembeve', max_length=255)),
                ('descriptioN', models.TextField()),
                ('foto', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
