# Generated by Django 4.0.5 on 2022-06-18 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0014_rezervo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervo',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Purchase Date(year/mm/day)'),
        ),
    ]
