# Generated by Django 4.0.5 on 2022-06-18 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0016_alter_rezervo_addresa_alter_rezervo_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervo',
            name='addresa',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='rezervo',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Purchase Date(year/mm/day)'),
        ),
        migrations.AlterField(
            model_name='rezervo',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='rezervo',
            name='lastname',
            field=models.CharField(max_length=255, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='rezervo',
            name='message',
            field=models.TextField(default='Message'),
        ),
        migrations.AlterField(
            model_name='rezervo',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
