# Generated by Django 4.0.5 on 2022-06-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0017_alter_rezervo_addresa_alter_rezervo_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervo',
            name='message',
            field=models.TextField(),
        ),
    ]
