# Generated by Django 4.0.5 on 2022-06-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0018_alter_rezervo_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervo',
            name='phonenumber',
            field=models.IntegerField(default='045', max_length=20),
        ),
    ]
