# Generated by Django 4.0.5 on 2022-06-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0021_alter_rezervo_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicesname', models.CharField(max_length=255, verbose_name='Services Name')),
                ('stage', models.CharField(default='1 times', max_length=255, verbose_name='Stage')),
                ('price', models.CharField(max_length=50, verbose_name='Prices')),
            ],
        ),
    ]
