# Generated by Django 4.0.5 on 2022-06-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0022_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='price',
            field=models.CharField(default=' euro', max_length=50, verbose_name='Prices'),
        ),
    ]
