# Generated by Django 4.0.5 on 2022-06-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0024_rezervo_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervo',
            name='color',
            field=models.CharField(choices=[('Heqja e një shtrese të vjetër, kurorë e vjetër', 'Heqja e një shtrese të vjetër, kurorë e vjetër'), ('Kurorë standarde prej porcelani dhe zirkoni në implant', 'Kurorë standarde prej porcelani dhe zirkoni në implant'), ('Implantimi i një implanti (çmimi varet nga sistemi i përdorur)', 'Implantimi i një implanti (çmimi varet nga sistemi i përdorur)'), ('Kurorë standarde prej porcelani dhe zirkoni në implant', 'Kurorë standarde prej porcelani dhe zirkoni në implant'), ('Mbulimi i recesionit të mishrave të dhëmbëve', 'Mbulimi i recesionit të mishrave të dhëmbëve'), ('Kurora dhe mbushje qeramike Porcelani dentar', 'Kurora dhe mbushje qeramike Porcelani dentar'), ('Shërbimi i zbardhjes së dhëmbëve në Klinikën Dentare', 'Shërbimi i zbardhjes së dhëmbëve në Klinikën Dentare'), ('Zbardhja e dhëmbëve me mbulesë (2 harqe)', 'Zbardhja e dhëmbëve me mbulesë (2 harqe)')], max_length=255),
        ),
    ]
