# Generated by Django 4.0.5 on 2022-09-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0027_alter_rezervo_sherbimi'),
    ]

    operations = [
        migrations.AddField(
            model_name='mendimi',
            name='lastname',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
