# Generated by Django 4.0.5 on 2022-09-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0029_alter_pricing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervo',
            name='addresa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
    ]
