# Generated by Django 4.0.5 on 2022-09-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0030_alter_rezervo_addresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervo',
            name='phonenumber',
            field=models.IntegerField(max_length=9),
        ),
    ]
