# Generated by Django 4.0.5 on 2022-09-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0032_alter_rezervo_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervo',
            name='koha',
            field=models.TimeField(default='00'),
        ),
    ]
