# Generated by Django 4.0.5 on 2023-02-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0034_remove_rezervo_koha'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
